[tool.poetry]
name = "agents-practises"
version = "0.1.0"
description = ""
authors = ["landshaft-band <kozlikoff2004@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
aiogram = "^3.30.0"
aiosqlite = "^0.22.1"
langchain = "^1.3.14"
langchain-community = "^0.4.2"
langchain-gigachat = "^0.5.1"
langchain-huggingface = "^1.2.2"
faiss-cpu = "^1.14.3"
pydantic-settings = "^2.14.2"
python-dotenv = "^1.2.2"

# Если вы напрямую импортируете SQLAlchemy, HTTPX или Requests — раскомментируйте:
# sqlalchemy = "^2.0.51"
# httpx = "^0.28.1"
# requests = "^2.34.2"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"